
server:
  port: 8222 # Gateway runs on port 8222

spring:
  application:
    name: gateway-service # Name of the service

  cloud:
    gateway:
      # CORS configuration
      globalcors:
        corsConfigurations:
          '[/**]': # Apply CORS to all paths
            allowedOrigins:
              - "http://localhost:3000" # Frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*" # Allow all headers
            allowCredentials: true # Allow cookies/auth headers

      # Define the routes for microservices
      routes:
        # Authentication Service
        - id: user-service
          uri: http://localhost:8090 # Backend auth service
          predicates:
            - Path=/api/v1/auth/**,/forgotPassword/**


        # user controller
        - id: user-service-profile
          uri: http://localhost:8090 # Backend auth service
          predicates:
            - Path=/api/v1/user
          filter:
            - AuthenticationFilter


# Eureka client configuration
eureka:
  client:
    register-with-eureka: false # Set to true if using Eureka for service discovery
    fetch-registry: false       # Fetch registry only if needed
